# Generated by Django 3.1.4 on 2021-10-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cant_familias', models.IntegerField(verbose_name='Cantidad Familias')),
                ('cant_paquetes', models.IntegerField(verbose_name='Cantidad Paquetes')),
                ('acceso_luz', models.CharField(max_length=50, verbose_name='Acceso Luz')),
                ('acceso_cloacas', models.CharField(max_length=50, verbose_name='Acceso Cloacas')),
                ('acceso_agua', models.CharField(max_length=50, verbose_name='Acceso Agua')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cant_barrios', models.IntegerField(verbose_name='Cantidad Barrios')),
                ('barrios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad', to='app.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('localidades', models.ManyToManyField(related_name='provincia', to='app.Localidad')),
            ],
        ),
    ]
