# Generated by Django 3.1.4 on 2021-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='cant_paquetes',
            field=models.IntegerField(default=0, verbose_name='Cantidad Barrios'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='cant_paquetes',
            field=models.IntegerField(default=0, verbose_name='Cantidad Paquetes'),
        ),
    ]
