# Generated by Django 3.1.4 on 2021-10-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211025_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='cant_familias',
            field=models.IntegerField(default=0, verbose_name='Cantidad Familias'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='cant_barrios',
            field=models.IntegerField(default=0, verbose_name='Cantidad Barrios'),
        ),
    ]
