# Generated by Django 3.1.4 on 2021-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211025_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='barrios',
        ),
        migrations.AddField(
            model_name='localidad',
            name='barrios',
            field=models.ManyToManyField(related_name='localidad', to='app.Barrio'),
        ),
    ]
