# Generated by Django 3.1.4 on 2021-10-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_localidad_cant_barrios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrio',
            old_name='acceso_cloacas',
            new_name='acceso_cloaca',
        ),
        migrations.RenameField(
            model_name='barrio',
            old_name='acceso_luz',
            new_name='acceso_electricidad',
        ),
    ]
